### ISSUE TITLE
Create java based DAO layer in front of Neo

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1127]
Scope:
- [x] Describe domain objects and actions - [Proposal](https://github.com/telstra/open-kilda/tree/develop/docs/design/domain-model)
- [x] Create sequence diagrams for DAO usage - [Proposal](https://github.com/telstra/open-kilda/tree/develop/docs/design/domain-model)
- [x] Create objects DTOs example per new model - #1398

Next task: #561

**Comment by nikitamarchenko** [comment]
@carmine [Proposal](https://github.com/nikitamarchenko/open-kilda/tree/dev/nmarchenko/domain-

**Comment by sergii-iakovenko** [comment]
### WBS

- [ ] Complete DAO implementation. **Est. 3-4d**
	- Complete implementation of TransactionManager
	- Complete design for TransitVlan, Rule, Meter and Ports.
	- SwitchRepository (delete by name / switch id)
	- FlowRepository (delete by flow id)
	- FlowSegmentRepository (delete by flow id, select by src+dest+flow id)
	- IslRepository
	- TransitVlanRepository
	- MeterRepository
	- PortRepository
	- RuleRepository
	
- [ ] Reimplement PathComputation to use DAO. **Est. 4-5d**
	- Suite of unit tests for PCE (NeoDriver + releated). Cover basic use-cases: single switch, 2 connected switches, with transit nodes.
	- AvailableNetwork (fetch the links)
	- NeoDriver (fetch the flows, fetch the switches, fetch the isls)

- [ ] Reimplement NeoOperationsBolt(s) **Est. 3d**
	- FlowOperationsBolt (no operations yet)
	- LinkOperationsBolt (fetch the links, fetch the link props)
	- SwitchOpearationsBolt (fetch the switches)
