### ISSUE TITLE
Move domain logic from storm to lib

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#1130]
Scope: 
- [x] Create a design guide (wiki) [proposal](https://github.com/nikitamarchenko/open-kilda/tree/dev/nmarchenko/storm-decouple/docs/design/storm-decouple)
- [x] Create POC/Example #328
- [x] add "Class diagram review" to the design guide #1312
- [x] Add to contribution documentations like "contrubutors guide" #1312

**Comment by pzakatov** [comment]
Scope: 
- [ ] Create a design guide (wiki)
- [ ] Create POC/Example

**Comment by pzakatov** [comment]
Related #25

**Comment by nikitamarchenko** [comment]
https://github.com/nikitamarchenko/open-kilda/tree/dev/nmarchenko/storm-decouple/docs/design/storm-decouple

**Comment by nikitamarchenko** [comment]
POC as part of #328
