### ISSUE TITLE
Implement switch rules synchronization in WFM.

### ISSUE THREAD

**Issue by dpoltavets** [telstra/open-kilda#1987]
To eliminate TE, we need to implement switch rules synchronization in WFM.

# Scope
- [x] analysis and design (2d)
- [x] wfm implementation (code, tests) (5-7d)
- [x] fix code review (1-2d)
