### ISSUE TITLE
Adopt existing Storm topologies to the data model with encapsulation support 

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#2018]
Re-implement the existing flow CRUD functionality to work with the new data model designed in #1466 and implemented in #1519 (PR - #2002)

**WBS**:
- [ ] Update CrudBolt with related Flow***Service(s) in Flow topology (2-3d)
- [ ] Update RerouteService in Reroute topology (< 1d)
- [ ] Update functional tests and testing (1-3d)

Total estimated efforts: 4 - 7d
