### ISSUE TITLE
issues in POST `/api/v2/flows`

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#2575]
- [x] can't set the 'description' field
- [x] can't create a pinned flow
- [x] system is allowing to create an one-switch flow on an DEACTIVATED switch(this issue is relevant for APIv1 too) #2576
- [x] can't create a flow on an Accton switch API #2460
- [x] can't create a protected flow #2459
- [x] can't specify a diverse flow id
- [x] needless transit vlan is being created #2455 (possibly is not relevant anymore)
- [x] an one-switch flow is not valid when it was created on a deactivated switch #2580 
- [ ] flow create events are not showing in kibana flow crud dashboard
- [x] can't to set the 'proiority' field
- [x] can't set the 'maxLatency' field
- [x] getFlow is not returning the 'diverse-with' field
- [x] POST `/api/v2/flows` is returning 500 instead of 409 in case flow conflict
- [x] able to create a flow on an ISL port(this issue is reproduced when port status is FAILED or MOVED)
- [x] unable to create default and simple flows when they are on the same port
- [x] incorrect priority is setting for cookies of default flow
