### ISSUE TITLE
Support Y-flows 

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#4589]
### Overview:
- As a user I'd like to create/update/delete a Y-flow. It's defined by 3 network endpoints. 
- Kilda allocates bandwidth for it, reroutes in a case of network changes and monitor the Y-flow state. 

#### Docs
- [x] Feature tech design. #4464

#### New switch rules / meters
- [x] Design new switch rules / meters for shared point and y-point. #4464

#### Northbound API
- [x] A new Y-flow API endpoint. #4437

#### Persistence
- [x] New Y-flow entities. #4530

#### PCE
- [x] Y-point calculation.
- [x] Affinity groups. #4549

#### Shared bandwidth
- [x] Introduce an ability for flow paths to share bandwidth. #4568 #4571

#### RuleManager
- [ ] Implement Y-point rules & meters.
- [ ] Integrate with Y-flow FSMs.

#### FlowHS topology - adapt to Y-flows
- [x] Reject Y-flow in Flow*** services. #4542
- [x] Forbid update ops for Y-flow sub-flows. #4542
- [x] Update Flow entity with Y-flow field support. #4542

#### FlowHS topology - refactor Flow*** FSMs
- [x] Introduce EventListener on Flow*** FSMs
- [x] New methods in Flow*** services to handle Y-flow requests

#### FlowHS topology - Create Y-flow FSM
- [x] New Service, Hub, FSM, up to 10 actions. #4502
- [x] Integration with Create Flow Service. #4502

#### FlowHS topology - Update Y-flow FSM
- [x] New Service, Hub, FSM, up to 10 actions. #4526
- [x] Handle Patch requests. #4526
- [x] Integration with Update Flow Service. #4526

#### FlowHS topology - Delete Y-flow FSM
- [x] New Service, Hub, FSM, up to 5 actions. #4534
- [x] Integration with Delete Flow Service. #4534

#### FlowHS topology - Reroute Y-flow FSM
- [ ] New Service, Hub, FSM, up to 15 actions.
- [ ] Integration with Reroute Flow Service.

#### FlowHS topology - Get Y-flow / sub-flows / paths
- [x] New Service, Hub, FSM, up to 5 actions. #4528

#### NBWorker topology (???) - YFlow validation
- [ ] New Service, Hub, FSM, up to 5 actions.
- [ ] Integration with Validation Flow Service.

#### Ping topology (???) - YFlow ping
- [ ] Forward request to Ping Flow Service. Aggregate results.

#### Reroute topology
- [x] Adapt RerouteQueue to YFlow. #4566

#### Testing
- [ ] Regression testing for Flow functionality.
- [ ] Functional tests (up to 20 scenarios) (EtE).

**Comment by sergii-iakovenko** [comment]
Y-flow support has been implemented.

**Comment by nikitamarchenko** [comment]
Congratulations!
