### ISSUE TITLE
BFD for Novi

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#569]
# BFD

BFD provides a low overhead mechanism for determining the health of a link where a link is defined as a path (could be physical or logical) between BFD enabled devices.  Within the confines of an OpenFlow network, BFD can be used to determine the health of a physical link directly connecting two switches.

Noviflow has added an extension to their OpenFlow implementation which allows two Noviflow switches to pass BFD packets and notify the OpenFlow controller when the link is down.  The BFD packets are sent and responded to directly on the switch with the role of the controller being

1. Setup the BFD session
2. Receive notifications when the BFD session is down

To setup the BFD session the controller must

1. Create a virtual interface on the switch of type BFD associating it with the physical port.

`set config logicalport logicalporttype bfd logicalportno 136 portno 16`

 Creates logical port 136 as a BFD port associated with physical port 16

2. Send a PACKET_OUT setting the parameters for the BFD session

```
struct of_action_noviflow_bfd_start : of_action_noviflow {
    uint16_t type == 0xFFFF;
    uint16_t len;
    uint32_t experimenter == 0xFF000002;
    uint8_t customer == 0xFF;
    uint8_t reserved == 0x00;
    uint16_t novi_action_type == 0x0004;
    uint32_t port_no;   // Logical port number created in step 1
    uint32_t my_disc;   // My discriminator
    uint32_t interval;    // BFD min tx and min rx interval in microseconds
    uint8_t multiplier;   // BFD multiplier
    uint8_t keepAliveTimeout; // Keep alive timeout flag. Value 0x00 indicates that the 
                             // BFD session is deleted after
                             // 10 * peer_multiplier * negotiated_rx_interval
                             // and Value 0x01 indicates infinite timeout
    pad(6);
}
```

3.  Install a match rule on both switches to respond to BFD packets matching on UDP destination of 3784 with an output of LOCAL.  **However to ensure that customers BFD packets can transit we need to find a way to identify the BFD packet as being ours.**

Once BFD is setup and started the switches will send the packets and only when a BFD session is considered down will an OF_PORT_DOWN event be sent to the OpenFlow Controller with the DOWN PORT being the Logical Port, the physical port will stay up.

In OF1.4 and greater Noviflow provides mechanisms to query the switch to obtain BFD status and will be addressed in future feature requests.

## Creating Logical Ports

The logical ports cannot be created via OpenFlow and will need to be created via the CLI or the gRPC.  For this purpose, a gRPC server will be created #1264  that can forward messages onto the switch.

As the PORT_DOWN message is associated with the logical port a mapping will be used such that logical ports for BFD will be calculated based on 2000 plus the physical port, such that physical port 20 will have a logical port of 2020.  This will need to be revisited for logical ports such as those associated with fan-out cables in the future.

**SEQUENCE DIAGRAM TO COME SOON**

## Scope
- [x] Implement switch features detector #1484 (PR #1502)
- [x] Implement BFD session management #1485 (PR #1660)
- [x] Event-topology refactoring #1343 (due to Dec/18)
- [x] Develop FSM for ISL capable to use BFD #1486 (due to Dec/24)
- [x] Add BFD support into event topology #1487 (due to Jan/4)

**Comment by pzakatov** [comment]
Current state for

- Implement switch features detector #1484 - on review
- Implement BFD session management #1485 - on review

- Event-topology refactoring #1343 - on design. Estimates 1-2 weeks for implementation

- Develop FSM for ISL capable to use BFD #1486 - depends on #1343. Estimate: 1-2 days
- Add BFD support into event topology #1487 - depends on #1486. Estimate: 1-2 weeks

**Comment by niksv** [comment]
BFD support was added to Kilda
