### ISSUE TITLE
Logging improvements for better monitoring and alerting

### ISSUE THREAD

**Issue by pzakatov** [telstra/open-kilda#588]
add object details to log records. 
- [ ] Everywhere: 
  - [ ] correlation ID. Should be mandatory for a log record. 
  - [ ] acion. Like CRUD, reroute, validate. OR
  - [ ] state. like Up, Down, Activated, etc.
  - [ ] reason for state change: User request or System event (like "port down"). e.g. reason type: external or internal. reason: CRUD, sw/isl/port down, etc.
- [ ] Flow related
  - [ ] flowID (e.g. in CRUD-Bolt, FlowImpl in NB)
  - [ ] source/destination sw-port-vlan 
- [ ] Switch-port related
  - [ ] switch ID, port
- [ ] ISL related
  - [ ] source/destination sw-port  

Other
- [ ] refactor logging in tpe-rest. It's always INFO
