### ISSUE TITLE
ATDD-Staging

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#700]
Basic:
- [x] Compare config defined sw to real
- [x] Compare config defined isl to real
- [x] Clean up procedure for hw sw

Discovery:
- [x] Check installed discovery rules on sw

Flow CRUD:
- [x] Create flows between all sw in topology
- [x] Read flows from NB
- [x] Update BW on flows
- [x] Check installed rules on sw (#702)
- [x] Check installed meters on sw (#701)
- [x] Check traffic BW - Implemented, Not Tested (#723)
- [x] Check update meters on sw (#701)
- [x] Check no traffic after delete flow (#723)
- [x] Check no rules after delete flow (#702)
- [x] Check no meters after delete flow (#712)

Reflow:
- [x] Create new API endpoint for intermediate sw (#790)
- [x] Reroute flow on broken ISL / Switch (#763)
- [x] Check old rules after reflow (#763)
- [x] Check new rules after reflow (#763)
