### ISSUE TITLE
ATDD-Staging: Add Floodlight Resilience Tests

### ISSUE THREAD

**Issue by rtretyak** [telstra/open-kilda#776]
This epic should fill the gap of missing resilience tests. By 'resilience tests' here we mean to verify correct system reaction to certain kinds of unexpected outages of different parts of the system.

- [ ] Caused by #117. Verify system behavior under certain load when speaker (Floodlight) suddenly loses connection to the rest of the system (Kafka -> Storm). System should successfully recover when speaker comes back
- [ ] Caused by #118.  Verify system behavior under certain load when speaker (Floodlight) restarts.
- [ ] Verify system behavior when floodlight loses connection to all switches (no reflow possibility)
